#+TITLE: Subliminal Emacs Config
#+AUTHOR: mattmc3
#+STARTUP: content
#+PROPERTY: header-args:emacs-lisp :tangle yes :results output silent

* Notes
This is an org mode literate config. Use <TAB> to expand sections, and put Emacs lisp in source blocks.

* Subliminal TODOs

** General
- [ ] Add mini-map
- [ ] Find/Replace shortcuts
- [ ] Configure multi-cursor
- [ ] File tree sidebar
- [ ] modeline (diminish)
- [ ] recent files (recentf)
- [ ] move between windows (groups in sublime)
- [ ] terminal (vterm/eshell)
- [ ] code folding
- [ ] indenting
- [ ] scratch buffer (sublima)
- [x] highlight line
- [x] ⌘-P for M-x
- [x] Add multiple cursor plugin
- [x] Save sessions

** Keybindings
- [ ] indent/dedent
- [ ] block comment
  
** Developer tools
- [ ] Magit
- [ ] LSP
- [ ] Treesitter

* Base Emacs Setup

** References
- [[https://github.com/hrs/sensible-defaults.el/blob/main/sensible-defaults.el][Sensible defaults]]

** Package management using use-package
[[https://github.com/jwiegley/use-package][use-package]]

We want to use external packages, so let's get that configured with use-package

#+begin_src emacs-lisp
  (defun subl/init-use-package ()
    (require 'package)

    (setq package-enable-at-startup nil)

    (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
    (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
    (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
    (add-to-list 'package-archives '("ublt" . "https://elpa.ubolonton.org/packages/") t)

    (package-initialize)

    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))

    (setq use-package-always-ensure t))

  (subl/init-use-package)
#+end_src

** UTF-8 all the things
#+begin_src emacs-lisp
  ;; default to utf-8 for all the things
  (set-charset-priority 'unicode)
  (setq locale-coding-system 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (set-selection-coding-system 'utf-8)
  (prefer-coding-system 'utf-8)
  (setq default-process-coding-system '(utf-8-unix . utf-8-unix))
#+end_src

** Better Emacs defaults
#+begin_src emacs-lisp
  ;; https://www.gnu.org/software/emacs/manual/html_node/elisp/Lexical-Binding.html
  (setq lexical-binding t)

  ;; The default is 600
  (setq max-lisp-eval-depth 2000)

  ;; Always load newest byte code
  (setq load-prefer-newer t)

  ;; reduce the frequency of garbage collection by making it happen on
  ;; each 50MB of allocated data (the default is on every 0.76MB)
  (setq gc-cons-threshold 50000000)

  ;; warn when opening files bigger than 100MB
  (setq large-file-warning-threshold 100000000)

  ;; always allow 'y' instead of 'yes'
  (defalias 'yes-or-no-p 'y-or-n-p)

  ;; smart tab behavior - indent or complete
  (setq tab-always-indent 'complete)

  ;; disable blink-matching-paren in favor of using colors
  (setq blink-matching-paren nil)
#+end_src

** Externally modified files
#+begin_src emacs-lisp
  ;; revert buffers automatically when underlying files are changed externally
  (global-auto-revert-mode t)
#+end_src

** GUI Chrome

*** Highlight current line
#+begin_src emacs-lisp
  (global-hl-line-mode +1)
#+end_src

*** Toolbar/Splash screen
#+begin_src emacs-lisp
  ;; let's not see the toolbar
  (tool-bar-mode -1)

  ;; turn off the splash screen
  (setq inhibit-splash-screen t)
#+end_src

*** Scrolling

[[https://www.emacswiki.org/emacs/SmoothScrolling][Smooth scrolling]]

#+begin_src emacs-lisp
  ;; set scrolling to be nicer
  (setq scroll-margin 30)
  (setq scroll-step 1)
  (setq scroll-conservatively 10000)
  (setq auto-window-vscroll nil)
#+end_src

*** Cursor
#+begin_src emacs-lisp
  ;; Make the cursor a bar, not a blinking box
  (setq-default cursor-type 'bar)
#+end_src

** Miscellaneous settings
#+begin_src emacs-lisp
  ;; write over selected text on input... like modern editors should
  (delete-selection-mode t)

  ;; Don't persist a custom file
  (setq custom-file null-device)         ; use a temp file as a placeholder
  (setq custom-safe-themes t)            ; mark all themes as safe, since we can't persist now
  (setq enable-local-variables :all)     ; fix =defvar= warnings

  ;; stop emacs from littering the file system with backup files
  (setq make-backup-files nil
        auto-save-default nil
        create-lockfiles nil)
#+end_src

** Emacs editor style
#+begin_src emacs-lisp
  ;; I like my cursor to be a bar, not a blinking box
  (setq-default cursor-type 'bar)

  ;; let's not see the toolbar
  (tool-bar-mode -1)

  ;; turn off the splash screen
  (setq inhibit-splash-screen t)

  ;; set scrolling to be nicer
  (setq scroll-margin 30)
  (setq scroll-step 1)
  (setq scroll-conservatively 10000)
  (setq auto-window-vscroll nil)
#+end_src

* Subliminal

There are some awesome things editors like Sublime Text has built in.
Let's add those behaviors to Emacs, either through plugins or through other means.

** Behaviors

*** Shell

#+begin_src emacs-lisp
  (defun subl/open-eshell ()
    "Open an eshell split"
    (interactive)
    (let ((w (split-window-below)))
      (select-window w)
      (eshell))
    (switch-to-buffer "*eshell*"))
#+end_src

*** Sorting

#+begin_src emacs-lisp :tangle no
  ;; https://stackoverflow.com/questions/20967818/emacs-function-to-case-insensitive-sort-lines/20967895
  (defun subl/sort-lines-nocase ()
    (interactive)
    (let ((sort-fold-case t))
      (call-interactively 'sort-lines)))
#+end_src

*** Insert line above/below

#+begin_src emacs-lisp
  (defun subl/insert-line-above ()
    "Insert a new line above the current one and go there"
    (interactive)
    (move-beginning-of-line nil)
    (newline-and-indent)
    (forward-line -1)
    (indent-according-to-mode))

  (defun subl/insert-line-below ()
    "Insert a new line below the current one and go there"
    (interactive)
    (move-end-of-line nil)
    (newline-and-indent)
    (indent-according-to-mode))
#+end_src

*** Join lines

#+begin_src emacs-lisp
  (defun subl/join-line ()
    "Join the line below with the current line"
    (interactive)
    (join-line -1))
#+end_src
*** Save all

#+begin_src emacs-lisp
  ; http://ergoemacs.org/emacs/emacs_auto_save.html
(defun subl/save-all-unsaved ()
  "Save all unsaved files without prompting"
  (interactive)
  (save-some-buffers t))
#+end_src

** Features

#+begin_src emacs-lisp
  (defun subl/init-save-all-on-focus-change ()
    (if (version< emacs-version "27")
      (add-hook 'focus-out-hook 'subl/save-all-unsaved)
    (setq after-focus-change-function 'subl/save-all-unsaved)))
#+end_src

** Restore sessions
#+begin_src emacs-lisp
  (desktop-save-mode 1)
#+end_src

** Sublime Keybindings
#+begin_src emacs-lisp
  (org-babel-load-file (expand-file-name "subliminal-keys.org" user-emacs-directory))
#+end_src

** Indent guides

#+begin_src emacs-lisp
  ;; indent with tabs, align with spaces where enabled
  (use-package smart-tabs-mode
    :ensure t)

  ;; add a visual intent guide
  (use-package highlight-indent-guides
    :ensure t
    :hook (prog-mode . highlight-indent-guides-mode)
    :custom
    (highlight-indent-guides-method 'character)
    (highlight-indent-guides-character ?|)
    (highlight-indent-guides-responsive 'stack))
#+end_src

** Multiple cursors

- [[https://emacs.stackexchange.com/questions/751/fundamentals-of-multiple-cursors][Multiple cursors stackexchange question]]
- [[http://emacsrocks.com/e13.html][Emacs Rocks]]

#+begin_src emacs-lisp
  (use-package multiple-cursors)
  (global-set-key (kbd "C->") 'mc/mark-next-like-this)
  (global-set-key (kbd "s-D") 'mc/mark-next-like-this-word)
  (global-set-key (kbd "s-L") 'mc/edit-ends-of-lines)
#+end_src

** Monokai theme
#+begin_src emacs-lisp
(use-package monokai-pro-theme
  :ensure t
  :config
  (load-theme 'monokai-pro t))
#+end_src

** All the icons

[[https://github.com/domtronn/all-the-icons.el][All the icons]]

#+begin_src emacs-lisp
  (use-package all-the-icons
    :ensure t)
#+end_src

** Minimap
#+begin_src emacs-lisp
  (use-package minimap
    :ensure t)
  ;; (minimap-mode)
#+end_src

** Buffer tabs
For buffer (file) tabs, we use the excellent [[https://github.com/ema2159/centaur-tabs][Centaur Tabs]] package.

#+begin_src emacs-lisp
  (use-package centaur-tabs
    :ensure t
    :demand
    :config
  (setq centaur-tabs-style "bar"
    centaur-tabs-height 24
    centaur-tabs-set-icons t
    centaur-tabs-set-modified-marker t
    ; centaur-tabs-show-navigation-buttons t
    centaur-tabs-gray-out-icons 'buffer
    centaur-tabs-set-bar 'over
          centaur-tabs-modified-marker "*"
    x-underline-at-descent-line t)
    (centaur-tabs-headline-match)
    (centaur-tabs-mode t)
    :bind
    ("C-<prior>" . centaur-tabs-backward)
    ("C-<next>" . centaur-tabs-forward))

  ;;(setq centaur-tabs-gray-out-icons 'buffer)
  ;;(setq centaur-tabs-style "slant")
#+end_src

* Run init
#+begin_src emacs-lisp
  (defun subl/init-subliminal ()
    "Run all the init functions for subliminal"
    (interactive)
    ;; (subl/init-use-package))
    (subl/init-save-all-on-focus-change))
  (subl/init-subliminal)
#+end_src
