#+TITLE: Subliminal Emacs
#+STARTUP: content
#+PROPERTY: header-args:emacs-lisp :tangle yes :results output silent

* Intro
Subliminal Emacs is an attempt to tame the Emacs beast with a modern and
familiar configuration rather than the out-of-the-box Emacs experience. Using
[[https://www.sublimetext.com][Sublime Text]] as a model, Subliminal sets
the behavior, menus, UI, and keybingings to a more familiar configuration.

Subliminal is meant to be a starter config that allows you to build your own
literal config from it using org-mode, but it is powerful and full featured
as-is.

** "This is the way" - The Mandalorian
- Emacs is a great editor and has stood the test of time
- Emacs is not configured very well out-of-the-box and adheres to its own outmodded standards
- Emacs is infinitely configurable, and configuring it to work the way you want it to is encouraged
- [[https://www.sublimetext.com][Other editors]] are also great, but may not be open source, or development is super slow, or may not stand the test of time
- Emacs can be adapted to work more like [[https://www.sublimetext.com][other editors]] to make it easier to adopt and learn
- Making Emacs work more like other editors is not wrong, and in fact can make Emacs accessible to more people
- When there's a reason to go back to "the old way", it should be easy to remove the custom configurations
- Emacs is your editor, use it your way!

** Installation
Subliminal is simply an org file that uses org-babel to tangle. If you're not
familiar with all that org-mode lingo, this simply means that the code needed to
configure emacs is embedded within this very documentation. To use Subliminal,
simply add the subliminal.org file to your Emacs directory, and add this line
to your init.el file:

#+begin_src emacs-lisp :tangle no
  (org-babel-load-file (expand-file-name "subliminal.org" user-emacs-directory))
  (subliminal/init)
#+end_src

** Notes
Subliminal uses org mode and the concept of a literate config. If editing in
Emacs Use <TAB> to expand sections, and put Emacs lisp in source blocks.

** Reference configs
- [[https://github.com/frap/emacs-literate/blob/master/readme.org][frap]]
- [[https://pages.sachachua.com/.emacs.d/Sacha.html][Sacha Chua]]
- [[https://github.com/purcell/emacs.d][Purcell]]
- [[https://github.com/hlissner/doom-emacs][Doom]]
- [[https://github.com/bbatsov/prelude][Prelude]]
- [[https://github.com/rougier/nano-emacs][N Λ N O]]
- [[https://github.com/natecox/dotfiles/blob/master/workspaces/shared/symlinks/emacs/.emacs.d/nathancox.org][Nate Cox]]

* Core
** Early init
In early-init.el, you will want to load subliminal-early.el. You can read more
about [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html][early-init.el here]].

In ~/.config/emacs/early-init.el or ~/.emacs.d/early-init.el add the following:
#+begin_src emacs-lisp :tangle no
  (load-file (expand-file-name "subliminal-early.el" user-emacs-directory))
#+end_src

#+begin_src emacs-lisp :tangle subliminal-early.el
  ;;; -*- lexical-binding: t; -*-
  (setq package-enable-at-startup nil)
#+end_src

Let's start off right with the lexical binding comment in the header. You can
read more about
[[https://www.gnu.org/software/emacs/manual/html_node/elisp/Lexical-Binding.html][lexical binding here.]]

** Lexical binding
#+begin_src emacs-lisp
  ;;; -*- lexical-binding: t; -*-
  (setq lexical-binding t)
#+end_src

** Better defaults
Some of the default values for Emacs variables are for a whole different era of
hardware or editing conventions. The core section if for changing built-in
variables to something more reasonable or modern. If you don't like these
values, you can always set them again after calling this function.

#+begin_src emacs-lisp
  (defun subliminal/init-core ()
    "Set variables to more modern defaults"
    ; https://github.com/bbatsov/prelude/blob/c52889dfa495583cb6d5204fa65b5b9ef0134866/init.el#L94-L99
    ; https://github.com/hrs/sensible-defaults.el/blob/main/sensible-defaults.el

    ; reduce the frequency of garbage collection by making it happen on
    ; each 50MB of allocated data (the default is on every 0.76MB)"
    (setq gc-cons-threshold 50000000)

    ; warn when opening files bigger than 100MB
    (setq large-file-warning-threshold 100000000)

    ; when opening a file, always follow symlinks."
    (setq vc-follow-symlinks t)

    ; treat CamelCaseWords as separate words in every programming mode
    (add-hook 'prog-mode-hook 'subword-mode)

    ; don't assume that sentences should have two spaces after periods
    (setq sentence-end-double-space nil)

    ; https://www.emacswiki.org/emacs/TransientMarkMode
    (transient-mark-mode t)

    ; if text is selected, and you type some text, delete the selected text
    ; like most other editors do
    (delete-selection-mode t)

    ;; revert buffers automatically when underlying files are changed externally
    (global-auto-revert-mode t)

    ;; always load newest byte code
    (setq load-prefer-newer t)

    ;; the default is 600
    (setq max-lisp-eval-depth 2000)

    ; when opening a file, start searching at the user's home directory
    (setq default-directory "~/")

    ;; add highlight for current line
    (global-hl-line-mode +1)

    ;; allow 'y/n' instead of 'yes/no'
    (defalias 'yes-or-no-p 'y-or-n-p))
#+end_src

* use-package
Not everything we need to make Emacs amazing is built in. We want to use
packages, so let's get that configured.

[[https://github.com/jwiegley/use-package][use-package]] is a nice way to
manage lazy loading our packages.

#+begin_src emacs-lisp
  (require 'package)

  (setq package-enable-at-startup nil)

  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
  (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
  (add-to-list 'package-archives '("ublt" . "https://elpa.ubolonton.org/packages/") t)

  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
  (setq use-package-always-ensure t)
#+end_src

* Unicode
Let's make sure that we are using UTF-8 for all the things.
#+begin_src emacs-lisp
  (defun subliminal/init-file-encoding ()
    ;; default to utf-8 for all the things
    (set-charset-priority 'unicode)
    (setq locale-coding-system   'utf-8)
    (prefer-coding-system        'utf-8)
    (set-default-coding-systems  'utf-8)
    (set-terminal-coding-system  'utf-8)
    (set-keyboard-coding-system  'utf-8)
    (set-language-environment    'utf-8)
    (set-selection-coding-system 'utf-8))
#+end_src

* User Interface
** Cursor
Most other editors do bars instead of a box for the cursor.
#+begin_src emacs-lisp
  (defun subliminal/init-cursor ()
    ;; make the cursor a bar, not a blinking box
    (setq-default cursor-type 'bar))
#+end_src

** Scrolling
[[https://www.emacswiki.org/emacs/SmoothScrolling][Smooth scrolling]]
#+begin_src emacs-lisp
  (defun subliminal/init-scrolling ()
    ;; hide scrollbars
    (scroll-bar-mode -1)
    ;; set scrolling to be nicer
    (setq scroll-margin 30)
    (setq scroll-step 1)
    (setq scroll-conservatively 10000)
    (setq auto-window-vscroll nil))
#+end_src

** Splash screen
Doom Emacs and other configs use a slash screen, but let's just jump right into
the editor.
#+begin_src emacs-lisp
  (defun subliminal/init-splash-screen ()
    ;; turn off the splash screen
    (setq inhibit-splash-screen t))
#+end_src

** Toolbar
Do away with the 90's era toolbar.
#+begin_src emacs-lisp
  (defun subliminal/init-toolbar ()
    ;; make the cursor a bar, not a blinking box
    (tool-bar-mode -1))
#+end_src

* Theme

#+begin_src emacs-lisp
  ; https://github.com/hlissner/emacs-doom-themes
  ; doom-city-lights
  (setq doom-theme 'doom-nord)
#+end_src

#+begin_src emacs-lisp
  (defun subliminal/init-theme ()
    (use-package doom-themes
      :config
      ;; Global settings (defaults)
      (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
            doom-themes-enable-italic t) ; if nil, italics is universally disabled

      ;; Enable flashing mode-line on errors
      (doom-themes-visual-bell-config)

      ;; Enable custom neotree theme (all-the-icons must be installed!)
      (doom-themes-neotree-config)
      ;; or for treemacs users
      (setq doom-themes-treemacs-theme "doom-colors") ; use the colorful treemacs theme
      (doom-themes-treemacs-config)

      ;; Corrects (and improves) org-mode's native fontification.
      (doom-themes-org-config))
      (load-theme doom-theme t))
#+end_src

* Features
** Save sessions
Saving sessions in Emacs is called saving the "desktop".
#+begin_src emacs-lisp
  (defun subliminal/init-save-sessions ()
    (desktop-save-mode 1))
#+end_src

** Autosave


** Customization file
You can save your personalized custom settings in another file.

#+begin_src emacs-lisp
  (defun subliminal/init-custom-file ()
    (setq custom-file (expand-file-name "myconfig.el" user-emacs-directory))
    (unless (file-exists-p custom-file)
      (write-region "" nil custom-file))
    (load-file custom-file))
#+end_src

Some examples of things you might want to add to that file:

#+begin_src emacs-lisp :tangle no
  ;; font
  (ignore-errors (set-frame-font "Meslo LG S for Powerline 13"))

  ;; trailing newlines are the bomb
  (setq require-final-newline t)
#+end_src








** Mac configuration
On a Mac, we want to use ⌘-Cmd as Super, and ⌥-Opt as Meta.
#+begin_src emacs-lisp
  (setq mac-option-key-is-meta t
        mac-command-key-is-meta nil
        mac-command-modifier 'super
        mac-option-modifier 'meta)
#+end_src

** Settings to sort later
#+begin_src emacs-lisp
  ;; default to utf-8 for all the things
  (set-charset-priority 'unicode)
  (setq locale-coding-system 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (set-selection-coding-system 'utf-8)
  (prefer-coding-system 'utf-8)
  (setq default-process-coding-system '(utf-8-unix . utf-8-unix))

  ;; Don't persist a custom file
  (setq custom-file null-device)         ; use a temp file as a placeholder
  (setq custom-safe-themes t)            ; mark all themes as safe, since we can't persist now
  (setq enable-local-variables :all)     ; fix =defvar= warnings

  ;; stop emacs from littering the file system with backup files
  (setq make-backup-files nil
  auto-save-default nil
  create-lockfiles nil)
#+end_src

* Org mode
#+begin_src emacs-lisp
  ;; https://emacs.stackexchange.com/questions/43656/make-c-s-up-handle-shift-selection-under-org-mode
  (setq org-support-shift-select t
  org-replace-disputed-keys t)
  (eval-after-load "org"
    '(progn
       (define-key org-mode-map (kbd "<S-up>") nil)
       (define-key org-mode-map (kbd "<S-down>") nil)
       (define-key org-mode-map (kbd "<M-S-left>") nil)
       (define-key org-mode-map (kbd "<M-S-right>") nil)
       (define-key org-mode-map (kbd "<M-left>") nil)
       (define-key org-mode-map (kbd "<M-right>") nil)
       (define-key org-mode-map [C-S-up] 'org-shiftup)
       (define-key org-mode-map [C-S-down] 'org-shiftdown)
       (define-key org-mode-map [C-S-right] 'org-shiftmetaright)
       (define-key org-mode-map [C-S-left] 'org-shiftmetaleft)
       (define-key org-mode-map [C-right] 'org-metaright)
       (define-key org-mode-map [C-left] 'org-metaleft)
       (define-key org-mode-map [C-S-return] 'org-insert-todo-heading)
       ))
#+end_src

* Subliminal
** Subliminal keybingings (CUA mode-ish)
#+begin_src emacs-lisp
  ;; Now, let's set up the Mac for some better CUA support
  ;; https://www.emacswiki.org/emacs/CuaMode - this isn't helpful on a Mac
  ;; (cua-mode t) ;; this is the Windows way, but the Mac uses command keys, so let's manually set that up
  ;; (global-set-key [(alt c)] 'kill-ring-save)
  ;; (global-set-key [(alt v)] 'yank)
  ;; (global-set-key [(alt x)] 'kill-region)
  ;; https://osdn.net/projects/macwiki/svn/view/zenitani/CarbonEmacs/src/lisp/mac-key-mode.el?root=macwiki&view=markup
  (global-set-key [(super up)] 'beginning-of-buffer)
  (global-set-key [(super down)] 'end-of-buffer)
  (global-set-key [(super left)] 'beginning-of-line)
  (global-set-key [(super right)] 'end-of-line)
  (global-set-key (kbd "s-s") 'save-buffer)
  (global-set-key (kbd "s-a") 'mark-whole-buffer)
  (global-set-key (kbd "s-z") 'undo)
  (global-set-key (kbd "s-c") 'kill-ring-save)
  (global-set-key (kbd "s-v") 'yank)
  (global-set-key (kbd "s-x") 'kill-region)
#+end_src

* Packages
** All the icons
#+begin_src emacs-lisp
  (use-package all-the-icons
    :ensure t)
#+end_src

** Centaur Tabs
[[https://github.com/ema2159/centaur-tabs][Centaur Tabs]]
#+begin_src emacs-lisp
  (use-package centaur-tabs
    :ensure t
    :demand
    :config
  (setq centaur-tabs-style "bar"
    centaur-tabs-height 24
    centaur-tabs-set-icons t
    centaur-tabs-set-modified-marker t
    ; centaur-tabs-show-navigation-buttons t
    centaur-tabs-gray-out-icons 'buffer
    centaur-tabs-set-bar 'over
          centaur-tabs-modified-marker "*"
    x-underline-at-descent-line t)
    (centaur-tabs-headline-match)
    (centaur-tabs-mode t)
    :bind
    ("C-<prior>" . centaur-tabs-backward)
    ("C-<next>" . centaur-tabs-forward))

  ;;(setq centaur-tabs-gray-out-icons 'buffer)
  ;;(setq centaur-tabs-style "slant")
#+end_src


* Init
Now that we've made all the Subliminal functions to bend Emacs to our will, it's
time to pull it all together.

#+begin_src emacs-lisp
(defun subliminal/init ()
  "Run all the init functions for subliminal"
  (interactive)
  (subliminal/init-core)
  (subliminal/init-file-encoding)
  (subliminal/init-custom-file)
  (subliminal/init-cursor)
  (subliminal/init-scrolling)
  (subliminal/init-splash-screen)
  (subliminal/init-toolbar)
  (subliminal/init-theme)
  (subliminal/init-save-sessions))
#+end_src

* Subliminal TODOs
- Add mini-map
- TODO Add multiple cursor plugin
- TODO Monokai theme
- TODO Find/Replace shortcuts
- TODO File tabs (centaur tabs)
- TODO Frame geometry
- TODO Save sessions
